spring:
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
    - org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
  datasource:
    url: 'jdbc:h2:mem:products'
    driverClassName: 'org.h2.Driver'
    username: 'dbuser'
    password: ''
  jpa:
    database-platform: 'org.hibernate.dialect.H2Dialect'
    hibernate:
      ddl-auto: 'create'
    show-sql: true
  mongodb:
    repositories:
      enabled: false
  h2:
    console:
      enabled: true
      path: '/h2-console'
      settings:
        web-allow-others: true

server:
  servlet:
    context-path: /api/v1
  tomcat:
    accept-count: 120
    mbeanregistry:
      enabled: true
    threads:
      max: 1200

service:
  database:
    embedded: true
