spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
        authentication-database: admin
        username: dbuser
        password: dbpass
        database: products
        port: 27017
        host: mongodb
  jpa:
    properties:
      hibernate:
        default_schema: 'events_test'
    show-sql: true
    repositories:
      enabled: false
service:
  database:
    embedded: false
